config/routes.rb
Rails.application.routes.draw do

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 管理者側のルーティング
  devise_for :admins, controllers: {
    sessions: 'admin/admins/sessions',
    registrations: 'admin/admins/registrations',
    passwords: 'admin/admins/passwords'
  }
  devise_scope :admin do
    post 'admins/guest_sign_in' => 'admin/admins/sessions#guest_sign_in'
  end
  
  namespace :admin do
    get 'homes/top' => 'homes#top'
    
    get 'searchs/search' => 'searchs#search'
    
    get 'groups/hashtag/:name' => 'groups#hashtag'
    
    resources :users, only: [:index, :show]
    
    resources :groups, only: [:index, :show, :destroy] do
      get 'members' => 'groups#members'
      resources :group_posts, only: [:show, :destroy]
    end
    
    resources :group_posts do
      resources :group_post_comments, only: [:destroy]
    end
    
    resources :genres, only: [:index, :show, :edit, :new, :create, :update, :destroy]
  end


  # ユーザー側のルーティング
  devise_for :users, controllers: {
    sessions: 'public/users/sessions',
    registrations: 'public/users/registrations',
    passwords: 'public/users/passwords',
    omniauth_callbacks: 'public/users/omniauth_callbacks'
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'public/users/sessions#guest_sign_in'
  end
  
  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    get 'homes/beginner'
    get 'homes/already_work'
    
    get 'searchs/search' => 'searchs#search'
    
    get 'groups/hashtag/:name' => 'groups#hashtag'
    
    get 'notifications/index' => 'notifications#index'
    
    resources :users, only: [:index, :show, :edit, :update] do
      get 'users/quit' => 'users#quit'
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    
    resources :groups, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      get 'join' => 'groups#join'
      delete 'unjoin' => 'groups#unjoin'
      get 'members' => 'groups#members'
      resources :group_posts, only: [:show, :new, :create, :edit, :update, :destroy]
    end
    
    resources :group_posts do
      resources :group_post_comments, only: [:create, :destroy]
      resources :group_post_favorites, only: [:create, :destroy]
    end
    
    resources :chats, only: [:show, :create]
    
    resources :genres, only: [:index, :show]
    
    get 'inquiries/index'
    post 'inquiries/create'
    post 'inquiries/confirm'
    get 'inquiries/thanks'
  
  end
end

app/models/group.rb
class Group < ApplicationRecord
  
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  
  has_many :admins, through: :group_admins
  
  has_many :group_posts, dependent: :destroy
  
  has_many :group_hashtags, dependent: :destroy
  has_many :hashtags, through: :group_hashtags
  
  # genreで.ownerを使うための記述
  belongs_to :owner, class_name: 'User'
  belongs_to :genre
  
  
  validates :name, presence: true, length: { maximum: 25 }
  validates :introduction, presence: true
  validates :genre_id, presence: true
  
  
  # 画像ファイルの付与
  attachment :group_image, destroy: false
  
  
  # グループを検索する時のメソッドを定義
  def self.search_for(content, method)
    if method == 'perfect'
      Group.where(name: content)
    elsif method == 'forword'
      Group.where('name LIKE ?', content + '%')
    elsif method == 'backword'
      Group.where('name LIKE ?', '%' + content)
    else
      Group.where('name LIKE ?', '%' + content + '%')
    end
  end
  
  
  # ハッシュタグ機能を作成時のアクションを定義
  after_create do
    group = Group.find_by(id: id)
    # hashbodyに打ち込まれたハッシュタグを検出
    hashtags = hashbody.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      # ハッシュタグは先頭の#を外した上で保存
      tag = Hashtag.find_or_create_by(name: hashtag.downcase.delete('#'))
      group.hashtags << tag
    end
  end
  # 更新時アクション
  before_update do
    group = Group.find_by(id: id)
    group.hashtags.clear
    hashtags = hashbody.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(name: hashtag.downcase.delete('#'))
      group.hashtags << tag
    end
  end
  

  # PV数表示機能の記述
  is_impressionable counter_cache: true
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @groups = Group.all.page(params[:page]).per(10)
  end

  def show
    @group = Group.find(params[:id])
    @hashname = @group.hashtags
    @tag = @group.hashtags.find_by(params[:name])
    @group_posts = @group.group_posts.page(params[:page]).per(10)
  end
  
  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to admin_groups_path, notice: "削除に成功しました"
  end
  
  # グループに紐づいたメンバーの一覧
  def members
    @group = Group.find(params[:group_id])
    @group_members = @group.users.page(params[:page]).per(10)
  end
  
  # ハッシュタグをクリック時その一覧を表示
  def hashtag
    @user = current_user
    @tag = Hashtag.find(params[:name])
    @groups = @tag.groups.page(params[:page]).per(10)
  end


  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image, :genre)
  end
  
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/views/admin/groups/_index.html.erb
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>コミュニティ画像</th>
      <th>コミュニティ名</th>
      <th>参加人数</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
    <tr>
      <td><%= attachment_image_tag group, :group_image, :fill, 60, 60, fallback: "no-image.png", size: "60x60", class:"rounded-circle" %></td>
      <td><%= group.name %></td>
      <td><%= group.group_users.count %></td>
      <td><%= link_to "詳細", admin_group_path(group) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/groups/hashtag.html.erb
<div class="container">
  <div class="row my-5">
    <h2 class="font-name">#<%= @tag.name %>一覧</h2>
    <div class="ml-auto"><%= render 'layouts/public_search' %></div>
  </div>
  
  <%= render 'public/groups/index', groups: @groups %>
  
  <div class="pagination">
    <%= paginate @groups %>
  </div>
  
</div>

app/views/admin/groups/index.html.erb
<div class="container">
  <div class="row my-5">
    <h2 class="font-name">コミュニティ一覧</h2>
    <div class="ml-auto"><%= render 'layouts/admin_search' %></div>
  </div>
  
  <%= render 'admin/groups/index', groups: @groups %>
  
  <div class="pagination">
    <%= paginate @groups %>
  </div>
  
</div>

app/views/admin/groups/members.html.erb
<div class="container">
  <div class="row my-5">
    <h2 class="font-name">参加ユーザー一覧</h2>
    <div class="ml-auto"><%= render 'layouts/public_search' %></div>
  </div>
  
  <%= render 'admin/users/index', users: @group_members %>
  
</div>

app/views/admin/groups/show.html.erb
<div class="container col-sm-8 col-10">
  <div class="row mt-4">
    <div><%= attachment_image_tag @group, :group_image, :fill, 80, 80, fallback: "no-image.png", size: "80x80", class:"rounded-circle" %></div>
    <h2 class="font-name name d-flex align-items-center ml-3 my-2">コミュニティ名：<%= @group.name %></h2>
  </div>

  <div>
    <% unless @tag == nil %>
      <% @hashname.each do |hashname| %>
        <%= link_to admin_path(hashname.id) do %>
          #<%= hashname.name %>
        <% end %>  
      <% end %>
    <% end %>
  </div>

  <div class="mt-2">
    <%= link_to "メンバー一覧", admin_group_members_path(@group), class:"font-name btn btn-info col-sm-4 col-10" %>
  </div>

  <div>
    <h4 class="font-name mt-3">概要</h4>
    <div class="card border-dark">
      <%= simple_format(Rinku.auto_link(@group.introduction, :all, 'target="_blank"').html_safe) %>
    </div>
  </div>

  <div class="row mt-5">
    <h4 class="font-name">投稿一覧</h4>
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th>タイトル</th>
          <th>投稿者</th>
          <th>コメント数</th>
          <th>PV数</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @group_posts.each do |group_post| %>
          <tr>
            <td><%= group_post.title %></td>
            <td><%= group_post.user.name %></td>
            <td><%= group_post.group_post_comment.count %></td>
            <td><%= group_post.impressionist_count(:filter=>:ip_address) %></td>
            <td><%= link_to "詳細", admin_group_group_post_path(@group, group_post) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row justify-content-center">
    <% if @group_posts.empty? %>
      <div class="pagination">投稿はありません</div>
    <% end %>
  </div>

  <div class="pagination">
    <%= paginate @group_posts %>
  </div>

  <div class="row justify-content-center my-4">
    <%= link_to "グループを削除する", admin_group_path(@group), method: :delete, "data-confirm" => "削除しますか？", class: "font-name btn btn-danger col-sm-3 col-8" %>
  </div>

</div>