config/routes.rb
Rails.application.routes.draw do

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 管理者側のルーティング
  devise_for :admins, controllers: {
    sessions: 'admin/admins/sessions',
    registrations: 'admin/admins/registrations',
    passwords: 'admin/admins/passwords'
  }
  devise_scope :admin do
    post 'admins/guest_sign_in' => 'admin/admins/sessions#guest_sign_in'
  end
  
  namespace :admin do
    get 'homes/top' => 'homes#top'
    
    get 'searchs/search' => 'searchs#search'
    
    get 'groups/hashtag/:name' => 'groups#hashtag'
    
    resources :users, only: [:index, :show]
    
    resources :groups, only: [:index, :show, :destroy] do
      get 'members' => 'groups#members'
      resources :group_posts, only: [:show, :destroy]
    end
    
    resources :group_posts do
      resources :group_post_comments, only: [:destroy]
    end
    
    resources :genres, only: [:index, :show, :edit, :new, :create, :update, :destroy]
  end


  # ユーザー側のルーティング
  devise_for :users, controllers: {
    sessions: 'public/users/sessions',
    registrations: 'public/users/registrations',
    passwords: 'public/users/passwords',
    omniauth_callbacks: 'public/users/omniauth_callbacks'
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'public/users/sessions#guest_sign_in'
  end
  
  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    get 'homes/beginner'
    get 'homes/already_work'
    
    get 'searchs/search' => 'searchs#search'
    
    get 'groups/hashtag/:name' => 'groups#hashtag'
    
    get 'notifications/index' => 'notifications#index'
    
    resources :users, only: [:index, :show, :edit, :update] do
      get 'users/quit' => 'users#quit'
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    
    resources :groups, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      get 'join' => 'groups#join'
      delete 'unjoin' => 'groups#unjoin'
      get 'members' => 'groups#members'
      resources :group_posts, only: [:show, :new, :create, :edit, :update, :destroy]
    end
    
    resources :group_posts do
      resources :group_post_comments, only: [:create, :destroy]
      resources :group_post_favorites, only: [:create, :destroy]
    end
    
    resources :chats, only: [:show, :create]
    
    resources :genres, only: [:index, :show]
    
    get 'inquiries/index'
    post 'inquiries/create'
    post 'inquiries/confirm'
    get 'inquiries/thanks'
  
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:twitter, :google_oauth2]
  
  # SNS認証のモデルとのアソシエーション
  has_many :sns_credentials

  # グループ機能のアソシエーション
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
  
  # グループ内での投稿のアソシエーション
  has_many :group_posts, dependent: :destroy
  
  # 投稿内でのコメント機能のアソシエーション
  has_many :group_post_comments, dependent: :destroy
  
  # 投稿内でのお気に入り機能のアソシエーション
  has_many :group_post_favorites, dependent: :destroy
  has_many :favorited_group_posts, through: :group_post_favorites, source: :group_post
  
  # フォローフォロワー機能のアソシエーション
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # チャット（DM）機能のアソシエーション
  has_many :user_rooms, dependent: :destroy 
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :user_rooms, dependent: :destroy
  
  # 通知機能のアソシエーション
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  

  validates :name, presence: true, length: { maximum: 25 }

  
  # 画像ファイルの付与
  attachment :profile_image, destroy: false
  
  
  # ゲストユーザーでのログイン機能を記述
  def self.guest
    find_or_create_by!(email: 'guest1user@example.com') do |user|
      user.name = 'guest'
      user.password = SecureRandom.urlsafe_base64
    end
  end
  

  # ユーザーを検索するときのメソッドを定義
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forword'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backword'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  
  
  # フォローフォロワー機能のメソッドを定義
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  
  # フォローフォロワー機能の通知のメソッドを定義
  def create_notification_follow(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
  
  
  
  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first
      if user.present?
        sns = SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
        )
      else
        user = User.new(
          name: auth.info.name,
          email: auth.info.email,
        )
        sns = SnsCredential.new(
          uid: auth.uid,
          provider: auth.provider
        )
      end
    return { user: user ,sns: sns}
  end

  def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
      unless user.present?
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email,
        )
      end
    return {user: user}
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
      if snscredential.present?
        user = with_sns_data(auth, snscredential)[:user]
        sns = snscredential
      else
        user = without_sns_data(auth)[:user]
        sns = without_sns_data(auth)[:sns]
      end
    return { user: user ,sns: sns}
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @groups = Group.all.page(params[:page]).per(10)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_index.html.erb
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>会員ID</th>
      <th>PF画像</th>
      <th>ニックネーム</th>
      <th>参加コミュニティ数</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no-image.png", size: "60x60", class:"rounded-circle" %></td>
      <td><%= user.name %></td>
      <td><%= user.groups.count %></td>
      <td><%= link_to "詳細", admin_user_path(user) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row my-5">
    <h2 class="font-name">ユーザー一覧</h2>
    <div class="ml-auto"><%= render 'layouts/admin_search' %></div>
  </div>

  <%= render 'admin/users/index', users: @users %>

  <div class="pagination">
    <%= paginate @users %>
  </div>

</div>

app/views/admin/users/show.html.erb
<div class="container col-sm-6 col-10">
  <div class="row mt-4">
    <div><%= attachment_image_tag @user, :profile_image, :fill, 80, 80, fallback: "no-image.png", size: "80x80", class:"rounded-circle" %></div>
    <div class="font-name d-flex align-items-center ml-3">チャンネル名：<%= @user.name %></div>
  </div>
  
  <div class="mt-4">
    <h4 class="font-name">概要</h4>
    <div class="card border-dark">
      <% if @user.introduction != nil %>
        <%= simple_format(Rinku.auto_link(@user.introduction, :all, 'target="_blank"').html_safe) %>
      <% else %>
        <%= @user.introduction %>
      <% end %>
    </div>
  </div>
  
  <div class="my-4">
    <h4 class="font-name">参加コミュニティ</h4>
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th>コミュニティ画像</th>
          <th>コミュニティ名</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @groups.each do |group| %>
        <tr>
          <td><%= attachment_image_tag group, :group_image, :fill, 60, 60, fallback: "no-image.png", size: "60x60", class:"rounded-circle" %></td>
          <td><%= group.name %></td>
          <td><%= link_to "詳細", admin_group_path(group) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>