config/routes.rb
Rails.application.routes.draw do

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 管理者側のルーティング
  devise_for :admins, controllers: {
    sessions: 'admin/admins/sessions',
    registrations: 'admin/admins/registrations',
    passwords: 'admin/admins/passwords'
  }
  devise_scope :admin do
    post 'admins/guest_sign_in' => 'admin/admins/sessions#guest_sign_in'
  end
  
  namespace :admin do
    get 'homes/top' => 'homes#top'
    
    get 'searchs/search' => 'searchs#search'
    
    get 'groups/hashtag/:name' => 'groups#hashtag'
    
    resources :users, only: [:index, :show]
    
    resources :groups, only: [:index, :show, :destroy] do
      get 'members' => 'groups#members'
      resources :group_posts, only: [:show, :destroy]
    end
    
    resources :group_posts do
      resources :group_post_comments, only: [:destroy]
    end
    
    resources :genres, only: [:index, :show, :edit, :new, :create, :update, :destroy]
  end


  # ユーザー側のルーティング
  devise_for :users, controllers: {
    sessions: 'public/users/sessions',
    registrations: 'public/users/registrations',
    passwords: 'public/users/passwords',
    omniauth_callbacks: 'public/users/omniauth_callbacks'
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'public/users/sessions#guest_sign_in'
  end
  
  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    get 'homes/beginner'
    get 'homes/already_work'
    
    get 'searchs/search' => 'searchs#search'
    
    get 'groups/hashtag/:name' => 'groups#hashtag'
    
    get 'notifications/index' => 'notifications#index'
    
    resources :users, only: [:index, :show, :edit, :update] do
      get 'users/quit' => 'users#quit'
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    
    resources :groups, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      get 'join' => 'groups#join'
      delete 'unjoin' => 'groups#unjoin'
      get 'members' => 'groups#members'
      resources :group_posts, only: [:show, :new, :create, :edit, :update, :destroy]
    end
    
    resources :group_posts do
      resources :group_post_comments, only: [:create, :destroy]
      resources :group_post_favorites, only: [:create, :destroy]
    end
    
    resources :chats, only: [:show, :create]
    
    resources :genres, only: [:index, :show]
    
    get 'inquiries/index'
    post 'inquiries/create'
    post 'inquiries/confirm'
    get 'inquiries/thanks'
  
  end
end

app/views/layouts/_admin_search.html.erb
<div class="search-form mt-2 col-sm-12 col-10">
  <%= form_with url: admin_searchs_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "会員"=> "user", "コミュニティ"=> "group", "ジャンル"=> "genre" }) %>
    <%= f.select :method, options_for_select({ "完全一致"=> "perfect", "前方一致"=> "forword", "後方一致"=> "backword", "部分一致"=> "partial"}) %>
    <%= f.submit "検索", class:"font-name btn btn-sm btn-info" %>
  <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation" class="text-danger">
    <h3><%= pluralize(obj.errors.count, "件") %>のエラーが発生しました </h3>
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row justify-content-center pt-3 pb-1 text-white">Copy right © kurikomi All Rights Reserved.</div>
    <div class="row justify-content-center py-3">
      <%= link_to "お問い合わせ", inquiries_index_path, class:"btn btn-secondary" %>
    </div>
    <div class="row justify-content-end">
      <% unless admin_signed_in? || user_signed_in? || current_user == Admin.guest %>
        <%= link_to "管理者ログインへ", new_admin_session_path, class:"text-white" %>
        <%= link_to "管理者ゲストログイン", admins_guest_sign_in_path, method: :post, class:"font-name btn btn-warning ml-3" %>
      <% end %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <div class="container py-2">
    <div class="row">
      <div class="mx-auto">
        <%= link_to "/" do %>
          <%= image_tag "logo.png", :class => "logo", :alt => "クリコミ", width: 200, class:"justify-content-center" %>
        <% end %>
      </div>
    </div>
    <div>
      <% if admin_signed_in? %>
        <ul class="nav nav-tabs justify-content-center nav-justified pt-3 pb-2">
          <li class="nav-item"><%= link_to "管理メニュー", admin_homes_top_path, class:"text-white" %></li>
          <li class="nav-item"><%= link_to "会員一覧", admin_users_path, class:"text-white" %></li>
          <li class="nav-item"><%= link_to "コミュニティ", admin_groups_path, class:"text-white" %></li>
          <li class="nav-item"><%= link_to "ジャンル一覧", admin_genres_path, class:"text-white" %></li>
          <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"text-white" %></li>
        </ul>
      <% elsif user_signed_in? %>
        <ul class="nav nav-tabs justify-content-center nav-justified pt-3 pb-2">
          <li class="nav-item"><%= link_to "マイページ", user_path(current_user), class:"text-white" %></li>
          <li class="nav-item">
            <%= link_to "通知", notifications_index_path, class:"text-white" %>
            <% if unchecked_notifications.any? %>
              <i class="fa fa-circle notification-circle" style="color: gold;"></i>
            <% end %>
          </li>
          <li class="nav-item"><%= link_to "会員一覧", users_path, class:"text-white" %></li>
          <li class="nav-item"><%= link_to "コミュニティ", groups_path, class:"text-white" %></li>
          <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"text-white" %></li>
        </ul>
      <% else %>
        <ul class="nav nav-tabs justify-content-center nav-justified pt-3 pb-2">
          <li class="nav-item"><%= link_to 'TOPページ', root_path, class:"text-white" %></li>
          <li class="nav-item"><%= link_to '概要', about_path, class:"text-white" %></li>
          <li class="nav-item"><%= link_to '新規登録', new_user_registration_path, class:"text-white" %></li>
          <li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class:"text-white" %></li>
        </ul>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/_public_search.html.erb
<div class="search-form mt-2 col-sm-12 col-10">
  <%= form_with url: searchs_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "会員"=> "user", "コミュニティ"=> "group", "ジャンル"=> "genre" }) %>
    <%= f.select :method, options_for_select({ "完全一致"=> "perfect", "前方一致"=> "forword", "後方一致"=> "backword", "部分一致"=> "partial"}) %>
    <%= f.submit "検索", class:"font-name btn btn-sm btn-info" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kurikomi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <%= favicon_link_tag('favicon.png') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div id="notice" class="bg-success text-center text-white"><%= notice %></div>
    <div id="alert" class="bg-danger text-center text-white"><%= alert %></div>
    <main>

      <%= yield %>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>